### ISSUE TITLE
Enhancement: Add prop to customize emitted element

### ISSUE THREAD

**Issue by greg-a-smith** [nanot1m/react-foco#2]
When using this package, it will automatically emit a `<span>` element in the DOM.  Not that this is terrible, but depending on where it is used, you could end up with `<div>` elements inside the `<span>`, which is not recommended.

What about adding a prop to define the emitted element and have the default be `<span>`?

**Comment by nanot1m** [comment]
Take a look at https://github.com/nanot1m/react-foco/pull/3
😊

**Comment by nanot1m** [comment]
Released react-foco@1.3.0

Give it a try (:
